export const getCart = {
    "id": 204165495,
    "billingAddressId": "00000000-0000-0000-0000-000000000000",
    "billingAddress": null,
    "shippingAddressId": "00000000-0000-0000-0000-000000000000",
    "shippingAddress": null,
    "shippingMethodId": 0,
    "totalPrice": "2.377,00",
    "totalTax": "362,59",
    "isCorporateAccount": false,
    "blockContinue": false,
    "isMontageAvailable": false,
    "isMontageSelected": false,
    "isGiftBoxSelected": false,
    "isGiftBoxOptionRestricted": false,
    "quantityOfItemInfo": "1 ürün",
    "isFreeShipping": false,
    "state": 1,
    "saleAgreement": null,
    "infoAgreement": null,
    "isAnonymous": true,
    "isAgreementChecked": false,
    "isShoppingLoanAvailable": true,
    "shoppingLoanSuggestionMessage": null,
    "isShoppingLoanPromotionBoxAvailable": true,
    "paymentInfoList": [],
    "canPayWithGiftcert": false,
    "payWithGiftcert": false,
    "detail": {
      "properties": {
        "isEvkurItemExists": "False",
        "isCartMixedForEvkur": "False",
        "allItemsAreEvkur": "False",
        "promotionList": "",
        "involvedCampaignIds": "65517,",
        "isItemCampaignIncludedMpProducts": "True",
        "isDueDateChangedByCampaign": "False",
        "isInstallmentSelling": "False",
        "canPayWithGiftcert": "False",
        "payWithGiftcert": "False",
        "hasGiftCertCampaign": "False",
        "giftCertInvolvedCampaignIds": "",
        "giftCertCampaignBasketMessages": "",
        "giftCertCampaignOrderConfirmationMessages": "",
        "threeDSecurePaymentEnabled": "False",
        "threeDSecurePaymentChecked": "False"
      },
      "prices": {
        "shippingPriceBeforeLateInterest": "0,00",
        "shippingTaxBeforeLateInterest": "0,00",
        "cartItemTotalPriceWithoutExtraFeePrice": "2.377,00",
        "extraFeePrice": "0,00",
        "giftBoxTotalAmount": "0,00",
        "totalPriceWithoutTax": "2.014,41",
        "totalPriceWithoutLateInterest": "2.377,00",
        "lateInterest": "0,00",
        "shippingPrice": "0,00",
        "shippingTax": "0,00",
        "shippingTaxRate": "0,00"
      }
    },
    "itemList": [
      {
        "id": 253141447,
        "sku": "HBV000002NTCX",
        "quantity": 1,
        "quantityFixed": false,
        "readOnly": false,
        "catalogName": "EE",
        "unitPrice": "2.377,00",
        "unitTax": "362,59",
        "price": "2.377,00",
        "tax": "362,59",
        "productImageUrl": "https://images.hepsiburada.net/assets/EE/80/9541054070834.jpg",
        "productPageUrl": "http://www.hepsiburada.com/lg-49lh590v-49-124-ekran-full-hd-uydu-alicili-smart-led-tv-p-HBV000002NTCX?magaza=teknobilisim",
        "typeCode": 4,
        "isCustomizedProduct": false,
        "customizedProductValue": null,
        "isAddedBySystem": false,
        "relatedCartItemIdList": null,
        "uniqueId": "c5d0a410-eb7c-4f2a-bd16-4e76f817120d",
        "customMerchant": null,
        "partnerProduct": {
          "companyId": 0,
          "createdProductCode": null,
          "previewUrl": null
        },
        "customizedProductProperties": {
          "sku": null,
          "displayName": null,
          "length": 0,
          "price": "0,00",
          "description": null
        },
        "detail": {
          "properties": {
            "isGiftBoxSelected": "False",
            "isCustomizedProduct": "False",
            "isAddedBySystem": "False",
            "orderOrigin": "WebSite",
            "addToListAvailable": "True",
            "name": "LG 49LH590V 49\" 124 Ekran Full HD Uydu Alıcılı Smart LED TV",
            "imageFileName": "9541054070834.jpg",
            "secureLinkFormat": "https://images.hepsiburada.net/assets/EE/{size}/9541054070834.jpg",
            "flags": "0",
            "variantOption": "",
            "isOnPublishing": "True",
            "isOnSelling": "True",
            "inStockDate": "",
            "freeShipment": "False",
            "fastShipping": "True",
            "estimatedShippingDay": "0",
            "installmentLimit": "6",
            "productAtDiscount": "False",
            "cargoOption": "0",
            "desi": "50",
            "export": "0",
            "isThirdParty": "True",
            "sapParty": "BANS",
            "sapStock": "7",
            "insuranceRate": "0",
            "extraFee": "0",
            "fixShippingPrice": "",
            "hasBargain": "False",
            "variantId": null,
            "filterFlag": "0",
            "warehouseId": "9999",
            "cityCodes": "",
            "barcode": "8806087778885",
            "sapProductType": "6807",
            "minimumQuantityForCart": "0",
            "maximumQuantityForCart": "0",
            "shipmentMethodId": "0",
            "shipmentMethodIdList": "[1]",
            "merchantUrl": "http://www.hepsiburada.com/magaza/teknobilisim",
            "estimatedShippingValueCart": "Yarın kargoda",
            "estimatedShippingValueOrderSummary": "Yarın kargoda",
            "estimatedShippingDate": "26.9.2017 14:59:18",
            "estimatedShippingDateForSameDay": "26.9.2017 14:59:18",
            "isEstimatedShippingDateCalculatedByStorefront": "True",
            "merchantName": "teknobilisim",
            "corporateName": "Yıldırım Elektronik San. Paz İth. İhr. LTD. ŞTİ.",
            "corporateAddress": "HOBYAR MAHALLESİ HAMİDİYE CADDESİ DOĞUBANK İŞ HANI KAT:2 NO :224 FATİH 34",
            "corporatePhone": "02125124365",
            "corporatePhoneFax": "2125273528",
            "vendorId": "7000005481",
            "commissionAmount": "106.97",
            "paymentTermInDays": "14",
            "dueDateTime": "26.9.2017 14:59:18",
            "mersisNumber": null,
            "commissionType": "0",
            "merchantCity": "",
            "isQuantityChangedByPipeline": "False",
            "isQuantityChangedByPipeline_Reason": "",
            "isLimitedStock": "False",
            "involvedCampaignId": "65517;65517;",
            "involvedLimit": ";1;",
            "freeShippingCampaignIdList": "65517",
            "campaignItemQuantity": "1;1;",
            "campaignType": "1;2;",
            "campaignDiscountValue": ";0;",
            "campaignDiscountTotal": ";0;",
            "itemPriceBeforeCampaignDiscount": ";2014,41;",
            "itemCampAwardInfoList": "[\"teknobilisim mağazasının seçili ürünlerinde kargo bedava!\"]",
            "itemCandidateFreeShippingCampAwardInfoList": "[]",
            "campaignLogItemList": "[{\"SKU\":\"HBV000002NTCX\",\"Quantity\":1,\"ConditionOrAward\":1,\"CampaignType\":6,\"CampaignId\":65517,\"CorrelationId\":\"a5cfaf3a-a16c-4b29-b4fc-593e34b9937e\",\"DiscountTotal\":0.0,\"ListingId\":\"c5d0a410-eb7c-4f2a-bd16-4e76f817120d\",\"IsConditionRegardedAsAward\":true,\"CampaignCreationType\":3},{\"SKU\":\"HBV000002NTCX\",\"Quantity\":1,\"ConditionOrAward\":2,\"CampaignType\":6,\"CampaignId\":65517,\"CorrelationId\":\"a5cfaf3a-a16c-4b29-b4fc-593e34b9937e\",\"DiscountTotal\":0.0,\"ListingId\":\"c5d0a410-eb7c-4f2a-bd16-4e76f817120d\",\"IsConditionRegardedAsAward\":true,\"CampaignCreationType\":3}]",
            "productId": "HB000002NTCW",
            "catalogName": "EE",
            "categoryId": "163192",
            "definitionName": "LCD Televizyon",
            "definitionId": "255",
            "brand": "LG",
            "stockLimit": "7",
            "discountEndDateTime": "1.1.0001 00:00:00",
            "categoryIdList": "2147483638 > 17201 > 163192 > 60000224 > 60003015 > 60005916 > 60005917 > 60000224 > 60008087 > 80131004 > 60000224 > 60008087 > 80137028 > 60000224 > 80138023 > 60000224 > 60008087 > 80138090 > 60000224 > 60008087 > 80139001 > 60000224 > 60008087 > 80139003 > 60000224 > 60008087 > 80143008 > 60000224 > 60008087 > 80146004 > 60000224 > 60008087 > 80153022 > 60000224 > 60008087 > 80154016 > 60000224 > 60008087 > 80156003 > 60000224 > 60008087 > 80156008 > 60000224 > 60008087 > 80158028 > 60000224 > 60008087 > 80161010 > 60000224 > 60008087 > 80161012 > 60000224 > 60008087 > 80169003 > 60000224 > 60008087 > 80185011 > 60000224 > 80186014 > 60000224 > 80218000 > 80218006 > 60000224 > 60008087 > 80227004 > 60000224 > 60008087 > 80248001 > 60000224 > 60008087 > 80272030",
            "categoryNameList": "Ev Elektroniği > Ses ve Görüntü Sistemleri > Televizyon, LED Ekran > Kampanyalar > Özel Sayfalar > LG > LG Televizyon > Kampanyalar > Ev Elektroniği Kampanyaları > 21 Aralık En Uzun Gecede Televizyon Fırsatları > Kampanyalar > Ev Elektroniği Kampanyaları > Askı Aparatı Hediyeli Televizyonlar  > Kampanyalar > En Uzun Gece > Kampanyalar > Ev Elektroniği Kampanyaları > Çok Satan Televizyonlarda Kampanya > Kampanyalar > Ev Elektroniği Kampanyaları > En Uzun Gece LG Televizyonlar > Kampanyalar > Ev Elektroniği Kampanyaları > LG Televizyonlarda Ekstra İndirimler  > Kampanyalar > Ev Elektroniği Kampanyaları > LG Televizyonlarda Özel Fiyatlar > Kampanyalar > Ev Elektroniği Kampanyaları > Çok Satan Televizyonlarda İndirim > Kampanyalar > Ev Elektroniği Kampanyaları > Büyük İnç Televizyonlarda Fırsatlar > Kampanyalar > Ev Elektroniği Kampanyaları > Dünya Devi Televizyon Markalarında İndirimler > Kampanyalar > Ev Elektroniği Kampanyaları > Seçili Televizyonlarda Kampanya > Kampanyalar > Ev Elektroniği Kampanyaları > En Çok Tercih Edilen TV’ ler > Kampanyalar > Ev Elektroniği Kampanyaları > LG Televizyonlarda Fırsatlar > Kampanyalar > Ev Elektroniği Kampanyaları > Televizyonlarda Şaşırtan Fırsatlar > Kampanyalar > Ev Elektroniği Kampanyaları > Televizyonlarda Kalite ve Uygun Fiyat > Kampanyalar > Ev Elektroniği Kampanyaları > Televizyonlarda Devam Eden Mega Fırsatlar > Kampanyalar > Ev Elektroniği Kampanyaları > Televizyonlarda %40' a Varan İndirimler Devam Ediyor > Kampanyalar > 21 Mart Kampanya > Kampanyalar > Dev Marka Festivali > Televizyon > Kampanyalar > Ev Elektroniği Kampanyaları > TV 40-60 ekran Kampanyası > Kampanyalar > Ev Elektroniği Kampanyaları > TV Askı Aparatı > Kampanyalar > Ev Elektroniği Kampanyaları > Mega Televizyon Kampanyası",
            "mainCategoryIdList": "2147483638 > 17201 > 163192",
            "mainCategoryNameList": "Ev Elektroniği > Ses ve Görüntü Sistemleri > Televizyon, LED Ekran",
            "stockQty": "7",
            "merchantId": "449ea369-d060-4ab9-9870-116947286757"
          },
          "prices": {
            "unitPriceBeforePrice": "0,00",
            "unitTaxBeforePrice": "0,00",
            "priceBeforePrice": "0,00",
            "taxBeforePrice": "0,00",
            "unitPriceAfterPrice": "2.377,00",
            "unitTaxAfterPrice": "362,59",
            "priceAfterPrice": "2.377,00",
            "taxAfterPrice": "362,59",
            "unitPriceBeforeExtraFee": "2.377,00",
            "unitTaxBeforeExtraFee": "362,59",
            "priceBeforeExtraFee": "2.377,00",
            "taxBeforeExtraFee": "362,59",
            "unitPriceAfterExtraFee": "2.377,00",
            "unitTaxAfterExtraFee": "362,59",
            "priceAfterExtraFee": "2.377,00",
            "taxAfterExtraFee": "362,59",
            "unitPriceWithoutTax": "2.014,41",
            "priceWithoutTax": "2.014,41",
            "unitExtraFeePrice": "0,00",
            "unitExtraFeePriceWithoutTax": "0,00",
            "extraFeePrice": "0,00",
            "extraFeePriceWithoutTax": "0,00",
            "unitBasePrice": "2.014,41",
            "unitPriceWithoutDiscount": "2.377,00",
            "priceWithoutDiscount": "2.377,00",
            "priceBeforeCampaignStage": "2.377,00",
            "taxBeforeCampaignStage": "362,59",
            "extraFeeBeforeCampaignStage": "0,00",
            "extraFeeTaxBeforeCampaignStage": "0,00",
            "priceAfterCampaignStage": "2.377,00",
            "taxAfterCampaignStage": "362,59",
            "extraFeeAfterCampaignStage": "0,00",
            "extraFeeTaxAfterCampaignStage": "0,00",
            "campaignDiscountAmount": "0,00",
            "campaignDiscountAmountWithoutTax": "0,00",
            "giftBoxPrice": "5,90",
            "giftBoxPriceWithoutTax": "5,00",
            "giftBoxUnitPriceWithoutTax": "5,00",
            "priceBeforeLateInterest": "2.377,00"
          }
        },
        "isDiscountWarningVisible": false,
        "remainingDaysForDiscount": -736596,
        "services": [],
        "giftBoxOption": {
          "isRestricted": true,
          "isGiftBoxSelected": false,
          "giftBoxItem": null,
          "giftBoxMessage": null
        }
      }
    ],
    "actionLogList": [
      {
        "actionTypeCode": 6,
        "name": "LG 49LH590V 49\" 124 Ekran Full HD Uydu Alıcılı Smart LED TV",
        "sku": "HBV000002NTCX",
        "catalogName": "EE",
        "productId": "HB000002NTCW",
        "message": "LG 49LH590V 49\" 124 Ekran Full HD Uydu Alıcılı Smart LED TV isimli üründen dolayı sepetinizdeki taksit sayısı 6 ile sınırlandırılmıştır."
      }
    ],
    "isLightboxErrorMessage": false,
    "extraFeePrice": "0,00",
    "cartItemPrice": "2.377,00",
    "shippingPrice": "5,00",
    "cartItemTotalQuantity": "1 ürün",
    "giftCertAmount": "0,00",
    "giftBoxAmount": "0,00",
    "partnerPoint": "0,00",
    "exceptionMessageList": [],
    "informationMessageList": [],
    "warningMessageList": [
      "LG 49LH590V 49\" 124 Ekran Full HD Uydu Alıcılı Smart LED TV isimli üründen dolayı sepetinizdeki taksit sayısı 6 ile sınırlandırılmıştır."
    ],
    "isValid": true,
    "success": true,
    "redirectionKey": null,
    "returnUrl": null,
    "trackingScript": "<script type=\"text/javascript\">\r\n $.cachedScript('//static.hepsiburada.net/scripts/webtrekkv16.js').done(function () {\r\n wto.server='production';\r\nif(wto.customParameter==null) { \r\n   wto.customParameter=new Array(); \r\n } \r\nwto.loggedIn='true';\r\nwto.customerId='{9a3f6c66-9006-4a27-bfba-ef57ec8ec47a}';\r\nwto.loginType='default';\r\nwto.pageName='www_hepsiburada_com.ayagina-gelsin.Cart.GetCart';\r\nwto.contentGroup={1:'Anasayfa'\r\n,2:'_Sepet'\r\n,3:'_Goruntuleme'\r\n,4:'GetCart'\r\n};\r\nwto.track();\r\n }); </script><script type=\"text/javascript\">\r\n</script>\r\n<script type=\"text/javascript\">\r\n var utag_data={\r\ncustomer_id:'9a3f6c66-9006-4a27-bfba-ef57ec8ec47a',\r\ncustomer_gender_id:'',\r\ncustomer_login_status:'logged in',\r\npage_name:'GetCart',\r\npage_domain:'www.hepsiburada.com',\r\npage_query_string:'',\r\npage_referring_url:'https://www.hepsiburada.com/ayagina-gelsin/sepetim',\r\npage_title:'Sepetim',\r\npage_url:'https://www.hepsiburada.com/ayagina-gelsin/Cart/GetCart',\r\npage_language:'tr-TR',\r\npage_site_region:'tr',\r\npage_site_name:'Hepsiburada',\r\nsite_type:'desktop',\r\nvisitor_type:'member',\r\npage_type:'cart',\r\nproduct_ids:'HB000002NTCW',\r\nproduct_names:'LG 49LH590V 49  124 Ekran Full HD Uydu Alicili Smart LED TV',\r\nproduct_quantities:'1',\r\nproduct_unit_prices:'2014.41',\r\nproduct_brands:'LG',\r\nproduct_skus:'HBV000002NTCX',\r\ncategory_id_hierarchy:'2147483638 > 17201 > 163192',\r\nproduct_category_ids:'163192',\r\ncategory_name_hierarchy:'Ev Elektronigi > Ses ve Goruntu Sistemleri > Televizyon LED Ekran',\r\nproduct_categories:'Ev Elektronigi > Ses ve Goruntu Sistemleri > Televizyon LED Ekran',\r\nisFashion :'false',\r\nfashionValue:'0'\r\n };\r\nHB.isVisilabsEnabled = false;\r\n</script>\r\n<script type=\"text/javascript\" src=\"//tags.tiqcdn.com/utag/hepsiburada/main/prod/utag.js\"></script>\r\n",
    "giftCertCode": null,
    "isGiftCertUsed": false,
    "partnerPoint": "0,00",
    "isPartnerPointUsed": false,
    "isGiftCertPriceSubtractedFromTotalPrice": true,
    "giftCertRefundDetailMessage": null
  }